apiVersion: apps/v1
kind: Deployment
metadata:
  name: timber-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timber-backend  
  template:
    spec:
      containers:
      - name: timber-backend
        image: eu.gcr.io/container-solutions-workshops/timber/backend:6f107b1c40f4100cb0b3078f157516863e345eec
        ports:
        - containerPort: 8080
