apiVersion: v1
kind: Service
metadata:
  labels:
    app: timber-backend
  name: timber-backend-np
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31000
    name: backend
  selector:
    app: timber-backend
  type: NodePort
